spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE?serverTimezone=Mexico/General&useSSL=false
spring.datasource.username=spring
spring.datasource.password=abc123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
