spring.datasource.url=jdbc:sqlserver://${PUSINEX_DB_SERVER};databaseName=${PUSINEX_DB_NAME}
spring.datasource.username=${PUSINEX_DB_USER}
spring.datasource.password=${PUSINEX_DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
