# Generated by Django 5.0.7 on 2024-07-29 19:02

import control.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('entidad', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('distrito', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('cabecera', models.TextField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('municipio', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.entidad')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'ordering': ['municipio'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('seccion', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'URBANO CONCENTRADO'), (2, 'URBANO(A)'), (3, 'MIXTO'), (4, 'RURAL'), (5, 'RURAL DISPERSO')])),
                ('activa', models.BooleanField(default=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.distrito')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.municipio')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['distrito__distrito', 'municipio__municipio', 'seccion'],
            },
        ),
        migrations.CreateModel(
            name='Pusinex2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_act', models.DateField()),
                ('hojas', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=control.models.pusinex_file)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.seccion')),
            ],
            options={
                'verbose_name': 'PUSINEX',
                'verbose_name_plural': 'PUSINEXs',
                'ordering': ['seccion__distrito__distrito', 'seccion__municipio__municipio', 'seccion__seccion'],
                'get_latest_by': ['f_act'],
            },
        ),
    ]
