# Generated by Django 4.1.5 on 2023-10-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_localidad_options_alter_municipio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pusinex',
            options={'ordering': ['seccion__distrito__distrito', 'seccion__seccion'], 'verbose_name': 'PUSINEX', 'verbose_name_plural': 'PUSINEXs'},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={'get_latest_by': ['f_act']},
        ),
        migrations.RemoveField(
            model_name='pusinex',
            name='localidad',
        ),
    ]
