# Generated by Django 4.1.5 on 2023-11-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_pusinex_options_alter_revision_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrito',
            name='id',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='id',
        ),
        migrations.AlterField(
            model_name='distrito',
            name='distrito',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='entidad',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='municipio',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='seccion',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
    ]
