# Generated by Django 4.1.5 on 2023-11-03 18:54

import control.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0004_remove_distrito_id_remove_entidad_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pusinex',
            options={'ordering': ['seccion__distrito__distrito', 'seccion__seccion'], 'verbose_name': 'PUSINEX_old', 'verbose_name_plural': 'PUSINEX_olds'},
        ),
        migrations.CreateModel(
            name='Pusinex2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_act', models.DateField()),
                ('hojas', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=control.models.pusinex_file)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.seccion')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PUSINEX',
                'verbose_name_plural': 'PUSINEXs',
                'ordering': ['seccion__distrito__distrito', 'seccion__municipio__municipio', 'seccion__seccion'],
                'get_latest_by': ['f_act'],
            },
        ),
    ]
