# Generated by Django 4.1.5 on 2023-11-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_pusinex_options_pusinex2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='pusinex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.pusinex2'),
        ),
    ]
