# Generated by Django 4.1.5 on 2023-11-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_revision_pusinex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='pusinex',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pusinex',
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
