# Generated by Django 4.1.5 on 2023-11-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_remove_revision_pusinex_remove_revision_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
