# Generated by Django 4.1.7 on 2024-07-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_seccion_activa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['distrito__distrito', 'municipio__municipio', 'seccion'], 'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
    ]
